apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    app: {{ .Values.appLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        {{- include "backend.labels" . | nindent 8 }}
        app: {{ .Values.appLabel }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "backend.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.repository.url }}:{{ .Values.repository.port }}/{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: po10-backend-configmap
            - secretRef:
                name: po10-backend-db-secret
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    app: {{ .Values.appLabel }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
    app: {{ .Values.appLabel }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.ingressRoute.name }}
  namespace: {{ .Values.namespace }}
spec:
  entrypoints:
    - web
  routes:
    - match: "Host(`{{ .Values.ingressRoute.host }}`)"
      kind: Rule
      services:
        - name: {{ .Values.service.name }}
          port: {{ .Values.service.port }}
