ARG NODE_VERSION=20

# stage 1: build
FROM node:${NODE_VERSION}

WORKDIR /parkrun-club

# Install git and openssh-client for git over SSH
RUN apt-get install git openssh-client

# Add the SSH key
COPY frontend/build_ssh_key /root/.ssh/id_rsa

# Set the correct permissions for the private key
RUN chmod 600 /root/.ssh/id_rsa

# Add GitHub's host key to known_hosts to prevent "Host key verification failed" errors
# Note: Replace github.com with your own Git server's domain if different

# RUN ssh-keyscan github.com >> /root/.ssh/known_hosts && \
#     chmod 644 /root/.ssh/known_hosts

# Clone your repository
# Note: Replace the URL with your repository's SSH URL

# RUN git clone git@github.com:jameswalden2/parkrun-club.git parkrun-club

RUN npm i vercel

COPY frontend/.vercel /parkrun-club/.vercel/

COPY frontend/package.json /parkrun-club/frontend/package.json
COPY frontend/src/prisma /parkrun-club/frontend/src/prisma
# RUN npm --prefix /parkrun-club/frontend install --production=false

COPY frontend/src /parkrun-club/frontend/src
COPY frontend/.eslintrc.json frontend/auth.config.ts frontend/auth.ts frontend/components.json frontend/next.config.js frontend/postcss.config.js frontend/tailwind.config.ts frontend/tsconfig.json /parkrun-club/frontend/

COPY frontend/build_script.sh /parkrun-club/frontend/build_script.sh
RUN chmod +x /parkrun-club/frontend/build_script.sh

RUN mkdir /parkrun-club/frontend/artifacts

ENTRYPOINT [ "sh", "/parkrun-club/frontend/build_script.sh" ]