# Default values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appLabel: parkrunclub.frontend

namespace: parkrunclub-local

replicaCount: 1

repository:
  url: "host.minikube.internal"
  port: "5001"

image:
  repository: parkrunclub-frontend
  pullPolicy: Always
  tag: "latest"

env:
  REACT_APP_BACKEND_SERVICE_NAME: parkrunclub-backend-service.parkrunclub-local.svc.cluster.local
  REACT_APP_BACKEND_PORT: 8000 # must match .Values.service.port in backend

service:
  name: parkrunclub-frontend-service
  type: ClusterIP
  port: 3000
  targetPort: 3000

ingressRoute:
  name: parkrunclub-frontend-ingress
  host: local.parkrunclub.com

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
